/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
*/

#import <AzureClientRuntime/AzureClientRuntime-umbrella.h>

/**
 * An object describing whether the image contains adult-oriented content
 * and/or is racy.
*/
@interface AdultInfo : NSObject <Codable>

    /**
     * A value indicating if the image contains adult-oriented content.
    */
    // json "isAdultContent"
    @property  AZBoolean* isAdultContent;

    /**
     * A value indicating if the image is race.
    */
    // json "isRacyContent"
    @property  AZBoolean* isRacyContent;

    /**
     * Score from 0 to 1 that indicates how much of adult content is within the
     * image.
    */
    // json "adultScore"
    @property  AZDouble* adultScore;

    /**
     * Score from 0 to 1 that indicates how suggestive is the image.
    */
    // json "racyScore"
    @property  AZDouble* racyScore;


@end
