/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

#import "AdultInfo.h"

@implementation AdultInfo

- (void)encodeWithCoder:(id<Coder>) encoder {

    [encoder encodeObject: self.isAdultContent forKey: @"isAdultContent"];
    [encoder encodeObject: self.isRacyContent forKey: @"isRacyContent"];
    [encoder encodeObject: self.adultScore forKey: @"adultScore"];
    [encoder encodeObject: self.racyScore forKey: @"racyScore"];

}

- (nullable instancetype)initWithDecoder:(id<Coder>)decoder {

    if (self = [super init]) {

        _isAdultContent = [decoder decodeObjectForKey:@"isAdultContent" objectClass:[AZBoolean class]];
        _isRacyContent = [decoder decodeObjectForKey:@"isRacyContent" objectClass:[AZBoolean class]];
        _adultScore = [decoder decodeObjectForKey:@"adultScore" objectClass:[AZDouble class]];
        _racyScore = [decoder decodeObjectForKey:@"racyScore" objectClass:[AZDouble class]];
    }

    return self;
}

@end
