/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
*/

#import <AzureClientRuntime/AzureClientRuntime-umbrella.h>
#import "CelebritiesModel.h"
#import "LandmarksModel.h"

/**
 * An object describing additional category details.
*/
@interface CategoryDetail : NSObject <Codable>

    /**
     * An array of celebrities if any identified.
    */
    // json "celebrities"
    @property  NSArray<CelebritiesModel*>* celebrities;

    /**
     * An array of landmarks if any identified.
    */
    // json "landmarks"
    @property  NSArray<LandmarksModel*>* landmarks;


@end
