/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

#import "Category.h"

@implementation Category

- (void)encodeWithCoder:(id<Coder>) encoder {

    [encoder encodeObject: self.name forKey: @"name"];
    [encoder encodeObject: self.score forKey: @"score"];
    [encoder encodeObject: self.detail forKey: @"detail"];

}

- (nullable instancetype)initWithDecoder:(id<Coder>)decoder {

    if (self = [super init]) {

        _name = [decoder decodeObjectForKey:@"name" objectClass:[NSString class]];
        _score = [decoder decodeObjectForKey:@"score" objectClass:[AZDouble class]];
        _detail = [decoder decodeObjectForKey:@"detail" objectClass:[CategoryDetail class]];
    }

    return self;
}

@end
