/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
*/

#import <AzureClientRuntime/AzureClientRuntime-umbrella.h>
#import "CategoryDetail.h"

/**
 * An object describing identified category.
*/
@interface Category : NSObject <Codable>

    /**
     * Name of the category.
    */
    // json "name"
    @property  NSString* name;

    /**
     * Scoring of the category.
    */
    // json "score"
    @property  AZDouble* score;

    /**
     * The detail property.
    */
    // json "detail"
    @property  CategoryDetail* detail;


@end
