/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
*/

#import <AzureClientRuntime/AzureClientRuntime-umbrella.h>
#import "FaceRectangle.h"

/**
 * An object describing possible celebrity identification.
*/
@interface CelebritiesModel : NSObject <Codable>

    /**
     * Name of the celebrity.
    */
    // json "name"
    @property  NSString* name;

    /**
     * Level of confidence ranging from 0 to 1.
    */
    // json "confidence"
    @property  AZDouble* confidence;

    /**
     * The faceRectangle property.
    */
    // json "faceRectangle"
    @property  FaceRectangle* faceRectangle;


@end
