/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

#import "ComputerVisionError.h"

@implementation ComputerVisionError

    - (id) initCode: (ComputerVisionErrorCodes *) code message: (NSString *) message {
        self = [super init];
        if (self) {
            _code = code;
            _message = message;
        }
        return self;
    }

- (void)encodeWithCoder:(id<Coder>) encoder {

    [encoder encodeObject: self.code forKey: @"code"];
    [encoder encodeObject: self.message forKey: @"message"];
    [encoder encodeObject: self.requestId forKey: @"requestId"];

}

- (nullable instancetype)initWithDecoder:(id<Coder>)decoder {

    if (self = [super init]) {

        _code = [decoder decodeObjectForKey:@"code" objectClass:[ComputerVisionErrorCodes class]];
        _message = [decoder decodeObjectForKey:@"message" objectClass:[NSString class]];
        _requestId = [decoder decodeObjectForKey:@"requestId" objectClass:[NSString class]];
    }

    return self;
}

@end
