/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

#import "CSCV_TextRecognitionMode.h"

/**
 * Defines values for CSCV_TextRecognitionMode.
 */
@implementation CSCV_TextRecognitionMode
+ (NSArray*)values {
    static NSArray *allValues;
    static dispatch_once_t onceToken;
    dispatch_once(&onceToken, ^{
        allValues = @[
            @"Handwritten",
            @"Printed"
        ];
    });
    return allValues;
}
/** Enum value Handwritten. */
+ (CSCV_TextRecognitionMode*)HANDWRITTEN {
    return [CSCV_TextRecognitionMode values][0];
}
/** Enum value Printed. */
+ (CSCV_TextRecognitionMode*)PRINTED {
    return [CSCV_TextRecognitionMode values][1];
}
+ (CSCV_TextRecognitionMode *)fromString:(NSString *)string {
    if (![[CSCV_TextRecognitionMode values]containsObject:string]) {
        @throw [NSException exceptionWithName:@"EnumCastException" reason:@"The string is not the enum member" userInfo:nil];
    }
    return (CSCV_TextRecognitionMode *)string;
}
+ (NSString *)toStringValue:(CSCV_TextRecognitionMode *)value {
    if (![[CSCV_TextRecognitionMode values]containsObject:value]) {
        @throw [NSException exceptionWithName:@"EnumCastException" reason:@"Enum value doesn't exist" userInfo:nil];
    }
    return (NSString *)value;
}
@end
