/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

#import <AzureClientRuntime/AzureClientRuntime.h>

/**
 * Defines values for CSCV_Gender.
 */
@interface CSCV_Gender : NSObject <AZStringEnum>
+ (NSArray*)values;
+ (NSString *)toStringValue:(CSCV_Gender *)value;
@property (class, readonly) CSCV_Gender *MALE;
@property (class, readonly) CSCV_Gender *FEMALE;
@end
