/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

#import "CSCV_ModelDescription.h"

@implementation CSCV_ModelDescription
- (void)encodeWithCoder:(id<AZCoder>)encoder {

    [encoder encodeObject:self.name forKey:@"name"];
    [encoder encodeObject:self.categories forKey:@"categories"];
}
- (nullable instancetype)initWithDecoder:(id<AZCoder>)decoder {

    if (self = [super init]) {
        _name = [decoder decodeObjectForKey:@"name" objectClass:[NSString class]];
        _categories = [decoder decodeArrayForKey:@"categories" elementClass:[NSString class]];
    }
    return self;
}
@end
