/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

#import "CSCV_ImageAnalysis.h"

@implementation CSCV_ImageAnalysis
- (void)encodeWithCoder:(id<AZCoder>)encoder {

    [encoder encodeObject:self.categories forKey:@"categories"];
    [encoder encodeObject:self.adult forKey:@"adult"];
    [encoder encodeObject:self.color forKey:@"color"];
    [encoder encodeObject:self.imageType forKey:@"imageType"];
    [encoder encodeObject:self.tags forKey:@"tags"];
    [encoder encodeObject:self.descriptionProperty forKey:@"description"];
    [encoder encodeObject:self.faces forKey:@"faces"];
    [encoder encodeObject:self.requestId forKey:@"requestId"];
    [encoder encodeObject:self.metadata forKey:@"metadata"];
}
- (nullable instancetype)initWithDecoder:(id<AZCoder>)decoder {

    if (self = [super init]) {
        _categories = [decoder decodeArrayForKey:@"categories" elementClass:[CSCV_Category class]];
        _adult = [decoder decodeObjectForKey:@"adult" objectClass:[CSCV_AdultInfo class]];
        _color = [decoder decodeObjectForKey:@"color" objectClass:[CSCV_ColorInfo class]];
        _imageType = [decoder decodeObjectForKey:@"imageType" objectClass:[CSCV_ImageType class]];
        _tags = [decoder decodeArrayForKey:@"tags" elementClass:[CSCV_ImageTag class]];
        _descriptionProperty = [decoder decodeObjectForKey:@"description" objectClass:[CSCV_ImageDescriptionDetails class]];
        _faces = [decoder decodeArrayForKey:@"faces" elementClass:[CSCV_FaceDescription class]];
        _requestId = [decoder decodeObjectForKey:@"requestId" objectClass:[NSString class]];
        _metadata = [decoder decodeObjectForKey:@"metadata" objectClass:[CSCV_ImageMetadata class]];
    }
    return self;
}
@end
