/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
*/

#import <AzureClientRuntime/AzureClientRuntime.h>

/**
 * An object providing additional metadata describing color attributes.
 */
@interface CSCV_ColorInfo : NSObject <AZCodable>
/**
 * Possible dominant foreground color.
 */
@property NSString *dominantColorForeground;
/**
 * Possible dominant background color.
 */
@property NSString *dominantColorBackground;
/**
 * An array of possible dominant colors.
 */
@property NSArray<NSString*> *dominantColors;
/**
 * Possible accent color.
 */
@property NSString *accentColor;
/**
 * A value indicating if the image is black and white.
 */
@property AZBoolean *isBWImg;
@end
