/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
*/

#import <AzureClientRuntime/AzureClientRuntime.h>
#import "CSCV_ComputerVisionErrorCodes.h"

/**
 * The CSCV_ComputerVisionError model.
 */
@interface CSCV_ComputerVisionError : NSObject <AZCodable>
/**
 * The error code. Possible values include: 'InvalidImageUrl',
 * 'InvalidImageFormat', 'InvalidImageSize', 'NotSupportedVisualFeature',
 * 'NotSupportedImage', 'InvalidDetails', 'NotSupportedLanguage',
 * 'BadArgument', 'FailedToProcess', 'Timeout', 'InternalServerError',
 * 'Unspecified', 'StorageException'.
 */
@property CSCV_ComputerVisionErrorCodes *code;
/**
 * A message explaining the error reported by the service.
 */
@property NSString *message;
/**
 * A unique request identifier.
 */
@property NSString *requestId;
/**
* Creates an instance of CSCV_ComputerVisionError class.
* @param code the error code. Possible values include: 'InvalidImageUrl', 'InvalidImageFormat', 'InvalidImageSize', 'NotSupportedVisualFeature', 'NotSupportedImage', 'InvalidDetails', 'NotSupportedLanguage', 'BadArgument', 'FailedToProcess', 'Timeout', 'InternalServerError', 'Unspecified', 'StorageException'.
* @param message a message explaining the error reported by the service.
*/
- (id) initWithCode:(CSCV_ComputerVisionErrorCodes *)code withmessage:(NSString *)message;
@end
