/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
*/

#import <AzureClientRuntime/AzureClientRuntime-umbrella.h>
#import "CSCV_ModelDescription.h"

/**
 * Result of the List Domain Models operation.
 */
@interface CSCV_ListModelsResult : NSObject <AZCodable>
/**
 * An array of supported models.
 */
@property (readonly) NSArray<CSCV_ModelDescription*> *modelsProperty;
/**
* Creates an instance of CSCV_ListModelsResult class.
*/
- (id) initWithmodelsProperty:(NSArray<CSCV_ModelDescription*> *)modelsProperty;
@end
