/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

#import "CSCV_ImageCaption.h"

@implementation CSCV_ImageCaption
- (void)encodeWithCoder:(id<AZCoder>)encoder {

    [encoder encodeObject:self.text forKey:@"text"];
    [encoder encodeObject:self.confidence forKey:@"confidence"];
}
- (nullable instancetype)initWithDecoder:(id<AZCoder>)decoder {

    if (self = [super init]) {
        _text = [decoder decodeObjectForKey:@"text" objectClass:[NSString class]];
        _confidence = [decoder decodeObjectForKey:@"confidence" objectClass:[AZDouble class]];
    }
    return self;
}
@end
