/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
*/

#import <AzureClientRuntime/AzureClientRuntime-umbrella.h>
#import "CSCV_LandmarksModel.h"
#import "CSCV_ImageMetadata.h"

/**
 * List of landmarks recognized in the image.
 */
@interface CSCV_LandmarkResults : NSObject <AZCodable>
/**
 * The landmarks property.
 */
@property NSArray<CSCV_LandmarksModel*> *landmarks;
/**
 * Id of the REST API request.
 */
@property NSString *requestId;
/**
 * The metadata property.
 */
@property CSCV_ImageMetadata *metadata;
@end
