/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
*/

#import <AzureClientRuntime/AzureClientRuntime.h>

/**
 * An object describing supported model by name and categories.
 */
@interface CSCV_ModelDescription : NSObject <AZCodable>
/**
 * The name property.
 */
@property NSString *name;
/**
 * The categories property.
 */
@property NSArray<NSString*> *categories;
@end
