/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
*/

#import <AzureClientRuntime/AzureClientRuntime-umbrella.h>

/**
 * The CSCV_ImageUrl model.
 */
@interface CSCV_ImageUrl : NSObject <AZCodable>
/**
 * Publicly reachable URL of an image.
 */
@property NSString *url;
/**
* Creates an instance of CSCV_ImageUrl class.
* @param url publicly reachable URL of an image.
*/
- (id) initWithurl:(NSString *)url;
@end
