/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

#import "CSCV_ColorInfo.h"

@implementation CSCV_ColorInfo
- (void)encodeWithCoder:(id<AZCoder>)encoder {

    [encoder encodeObject:self.dominantColorForeground forKey:@"dominantColorForeground"];
    [encoder encodeObject:self.dominantColorBackground forKey:@"dominantColorBackground"];
    [encoder encodeObject:self.dominantColors forKey:@"dominantColors"];
    [encoder encodeObject:self.accentColor forKey:@"accentColor"];
    [encoder encodeObject:self.isBWImg forKey:@"isBWImg"];
}
- (nullable instancetype)initWithDecoder:(id<AZCoder>)decoder {

    if (self = [super init]) {
        _dominantColorForeground = [decoder decodeObjectForKey:@"dominantColorForeground" objectClass:[NSString class]];
        _dominantColorBackground = [decoder decodeObjectForKey:@"dominantColorBackground" objectClass:[NSString class]];
        _dominantColors = [decoder decodeArrayForKey:@"dominantColors" elementClass:[NSString class]];
        _accentColor = [decoder decodeObjectForKey:@"accentColor" objectClass:[NSString class]];
        _isBWImg = [decoder decodeObjectForKey:@"isBWImg" objectClass:[AZBoolean class]];
    }
    return self;
}
@end
