/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

#import "CSCV_ImageUrl.h"

@implementation CSCV_ImageUrl
    - (id) initWithurl:(NSString *)url {
        self = [super init];
        if (self) {
            _url = url;
        }
        return self;
    }
- (void)encodeWithCoder:(id<AZCoder>)encoder {

    [encoder encodeObject:self.url forKey:@"url"];
}
- (nullable instancetype)initWithDecoder:(id<AZCoder>)decoder {

    if (self = [super init]) {
        _url = [decoder decodeObjectForKey:@"url" objectClass:[NSString class]];
    }
    return self;
}
@end
