/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

#import "CSCV_Details.h"

/**
 * Defines values for CSCV_Details.
 */
@implementation CSCV_Details
+ (NSArray*)values {
    static NSArray *allValues;
    static dispatch_once_t onceToken;
    dispatch_once(&onceToken, ^{
        allValues = @[
            @"Celebrities",
            @"Landmarks"
        ];
    });
    return allValues;
}
/** Enum value Celebrities. */
+ (CSCV_Details*)CELEBRITIES {
    return [CSCV_Details values][0];
}
/** Enum value Landmarks. */
+ (CSCV_Details*)LANDMARKS {
    return [CSCV_Details values][1];
}
+ (CSCV_Details *)fromString:(NSString *)string {
    if (![[CSCV_Details values]containsObject:string]) {
        @throw [NSException exceptionWithName:@"EnumCastException" reason:@"The string is not the enum member" userInfo:nil];
    }
    return (CSCV_Details *)string;
}
+ (NSString *)toStringValue:(CSCV_Details *)value {
    if (![[CSCV_Details values]containsObject:value]) {
        @throw [NSException exceptionWithName:@"EnumCastException" reason:@"Enum value doesn't exist" userInfo:nil];
    }
    return (NSString *)value;
}
@end
