/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

#import "CSCV_ImageDescriptionDetails.h"

@implementation CSCV_ImageDescriptionDetails
- (void)encodeWithCoder:(id<AZCoder>)encoder {

    [encoder encodeObject:self.tags forKey:@"tags"];
    [encoder encodeObject:self.captions forKey:@"captions"];
}
- (nullable instancetype)initWithDecoder:(id<AZCoder>)decoder {

    if (self = [super init]) {
        _tags = [decoder decodeArrayForKey:@"tags" elementClass:[NSString class]];
        _captions = [decoder decodeArrayForKey:@"captions" elementClass:[CSCV_ImageCaption class]];
    }
    return self;
}
@end
