/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

#import <AzureClientRuntime/AzureClientRuntime-umbrella.h>

/**
 * Defines values for CSCV_ComputerVisionErrorCodes.
 */
@interface CSCV_ComputerVisionErrorCodes : NSObject <AZStringEnum>
+ (NSArray*)values;
+ (NSString *)toStringValue:(CSCV_ComputerVisionErrorCodes *)value;
@property (class, readonly) CSCV_ComputerVisionErrorCodes *INVALID_IMAGE_URL;
@property (class, readonly) CSCV_ComputerVisionErrorCodes *INVALID_IMAGE_FORMAT;
@property (class, readonly) CSCV_ComputerVisionErrorCodes *INVALID_IMAGE_SIZE;
@property (class, readonly) CSCV_ComputerVisionErrorCodes *NOT_SUPPORTED_VISUAL_FEATURE;
@property (class, readonly) CSCV_ComputerVisionErrorCodes *NOT_SUPPORTED_IMAGE;
@property (class, readonly) CSCV_ComputerVisionErrorCodes *INVALID_DETAILS;
@property (class, readonly) CSCV_ComputerVisionErrorCodes *NOT_SUPPORTED_LANGUAGE;
@property (class, readonly) CSCV_ComputerVisionErrorCodes *BAD_ARGUMENT;
@property (class, readonly) CSCV_ComputerVisionErrorCodes *FAILED_TO_PROCESS;
@property (class, readonly) CSCV_ComputerVisionErrorCodes *TIMEOUT;
@property (class, readonly) CSCV_ComputerVisionErrorCodes *INTERNAL_SERVER_ERROR;
@property (class, readonly) CSCV_ComputerVisionErrorCodes *UNSPECIFIED;
@property (class, readonly) CSCV_ComputerVisionErrorCodes *STORAGE_EXCEPTION;
@end
