/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
*/

#import <AzureClientRuntime/AzureClientRuntime-umbrella.h>

/**
 * An object describing face rectangle.
 */
@interface CSCV_FaceRectangle : NSObject <AZCodable>
/**
 * X-coordinate of the top left point of the face.
 */
@property AZInteger *left;
/**
 * Y-coordinate of the top left point of the face.
 */
@property AZInteger *top;
/**
 * Width measured from the top-left point of the face.
 */
@property AZInteger *width;
/**
 * Height measured from the top-left point of the face.
 */
@property AZInteger *height;
@end
