/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
*/

#import <AzureClientRuntime/AzureClientRuntime-umbrella.h>

/**
 * Image metadata.
 */
@interface CSCV_ImageMetadata : NSObject <AZCodable>
/**
 * Image width.
 */
@property AZInteger *width;
/**
 * Image height.
 */
@property AZInteger *height;
/**
 * Image format.
 */
@property NSString *format;
@end
