/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

#import "CSCV_CelebrityResults.h"

@implementation CSCV_CelebrityResults
- (void)encodeWithCoder:(id<AZCoder>)encoder {

    [encoder encodeObject:self.celebrities forKey:@"celebrities"];
    [encoder encodeObject:self.requestId forKey:@"requestId"];
    [encoder encodeObject:self.metadata forKey:@"metadata"];
}
- (nullable instancetype)initWithDecoder:(id<AZCoder>)decoder {

    if (self = [super init]) {
        _celebrities = [decoder decodeArrayForKey:@"celebrities" elementClass:[CSCV_CelebritiesModel class]];
        _requestId = [decoder decodeObjectForKey:@"requestId" objectClass:[NSString class]];
        _metadata = [decoder decodeObjectForKey:@"metadata" objectClass:[CSCV_ImageMetadata class]];
    }
    return self;
}
@end
