/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
*/

#import <AzureClientRuntime/AzureClientRuntime-umbrella.h>
#import "CSCV_ImageCaption.h"
#import "CSCV_ImageMetadata.h"

/**
 * A collection of content tags, along with a list of captions sorted by
 * confidence level, and image metadata.
 */
// Needs Flatten
@interface CSCV_ImageDescription : NSObject <AZCodable>
/**
 * A collection of image tags.
 */
@property NSArray<NSString*> *tags;
/**
 * A list of captions, sorted by confidence level.
 */
@property NSArray<CSCV_ImageCaption*> *captions;
/**
 * Id of the REST API request.
 */
@property NSString *requestId;
/**
 * The metadata property.
 */
@property CSCV_ImageMetadata *metadata;
@end
