/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
*/

#import <AzureClientRuntime/AzureClientRuntime.h>
#import "CSCV_FaceRectangle.h"

/**
 * An object describing possible celebrity identification.
 */
@interface CSCV_CelebritiesModel : NSObject <AZCodable>
/**
 * Name of the celebrity.
 */
@property NSString *name;
/**
 * Level of confidence ranging from 0 to 1.
 */
@property AZDouble *confidence;
/**
 * The faceRectangle property.
 */
@property CSCV_FaceRectangle *faceRectangle;
@end
