/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

#import "CSCV_VisualFeatureTypes.h"

/**
 * Defines values for CSCV_VisualFeatureTypes.
 */
@implementation CSCV_VisualFeatureTypes
+ (NSArray*)values {
    static NSArray *allValues;
    static dispatch_once_t onceToken;
    dispatch_once(&onceToken, ^{
        allValues = @[
            @"ImageType",
            @"Faces",
            @"Adult",
            @"Categories",
            @"Color",
            @"Tags",
            @"Description"
        ];
    });
    return allValues;
}
/** Enum value ImageType. */
+ (CSCV_VisualFeatureTypes*)IMAGE_TYPE {
    return [CSCV_VisualFeatureTypes values][0];
}
/** Enum value Faces. */
+ (CSCV_VisualFeatureTypes*)FACES {
    return [CSCV_VisualFeatureTypes values][1];
}
/** Enum value Adult. */
+ (CSCV_VisualFeatureTypes*)ADULT {
    return [CSCV_VisualFeatureTypes values][2];
}
/** Enum value Categories. */
+ (CSCV_VisualFeatureTypes*)CATEGORIES {
    return [CSCV_VisualFeatureTypes values][3];
}
/** Enum value Color. */
+ (CSCV_VisualFeatureTypes*)COLOR {
    return [CSCV_VisualFeatureTypes values][4];
}
/** Enum value Tags. */
+ (CSCV_VisualFeatureTypes*)TAGS {
    return [CSCV_VisualFeatureTypes values][5];
}
/** Enum value Description. */
+ (CSCV_VisualFeatureTypes*)DESCRIPTION {
    return [CSCV_VisualFeatureTypes values][6];
}
+ (CSCV_VisualFeatureTypes *)fromString:(NSString *)string {
    if (![[CSCV_VisualFeatureTypes values]containsObject:string]) {
        @throw [NSException exceptionWithName:@"EnumCastException" reason:@"The string is not the enum member" userInfo:nil];
    }
    return (CSCV_VisualFeatureTypes *)string;
}
+ (NSString *)toStringValue:(CSCV_VisualFeatureTypes *)value {
    if (![[CSCV_VisualFeatureTypes values]containsObject:value]) {
        @throw [NSException exceptionWithName:@"EnumCastException" reason:@"Enum value doesn't exist" userInfo:nil];
    }
    return (NSString *)value;
}
@end
