/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

#import <AzureClientRuntime/AzureClientRuntime.h>

/**
 * Defines values for CSCV_OcrLanguages.
 */
@interface CSCV_OcrLanguages : NSObject <AZStringEnum>
+ (NSArray*)values;
+ (NSString *)toStringValue:(CSCV_OcrLanguages *)value;
@property (class, readonly) CSCV_OcrLanguages *UNK;
@property (class, readonly) CSCV_OcrLanguages *ZH_HANS;
@property (class, readonly) CSCV_OcrLanguages *ZH_HANT;
@property (class, readonly) CSCV_OcrLanguages *CS;
@property (class, readonly) CSCV_OcrLanguages *DA;
@property (class, readonly) CSCV_OcrLanguages *NL;
@property (class, readonly) CSCV_OcrLanguages *EN;
@property (class, readonly) CSCV_OcrLanguages *FI;
@property (class, readonly) CSCV_OcrLanguages *FR;
@property (class, readonly) CSCV_OcrLanguages *DE;
@property (class, readonly) CSCV_OcrLanguages *EL;
@property (class, readonly) CSCV_OcrLanguages *HU;
@property (class, readonly) CSCV_OcrLanguages *IT;
@property (class, readonly) CSCV_OcrLanguages *JA;
@property (class, readonly) CSCV_OcrLanguages *KO;
@property (class, readonly) CSCV_OcrLanguages *NB;
@property (class, readonly) CSCV_OcrLanguages *PL;
@property (class, readonly) CSCV_OcrLanguages *PT;
@property (class, readonly) CSCV_OcrLanguages *RU;
@property (class, readonly) CSCV_OcrLanguages *ES;
@property (class, readonly) CSCV_OcrLanguages *SV;
@property (class, readonly) CSCV_OcrLanguages *TR;
@property (class, readonly) CSCV_OcrLanguages *AR;
@property (class, readonly) CSCV_OcrLanguages *RO;
@property (class, readonly) CSCV_OcrLanguages *SR_CYRL;
@property (class, readonly) CSCV_OcrLanguages *SR_LATN;
@property (class, readonly) CSCV_OcrLanguages *SK;
@end
