/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

#import "CSCV_FaceDescription.h"

@implementation CSCV_FaceDescription
- (void)encodeWithCoder:(id<AZCoder>)encoder {

    [encoder encodeObject:self.age forKey:@"age"];
    [encoder encodeObject:self.gender forKey:@"gender"];
    [encoder encodeObject:self.faceRectangle forKey:@"faceRectangle"];
}
- (nullable instancetype)initWithDecoder:(id<AZCoder>)decoder {

    if (self = [super init]) {
        _age = [decoder decodeObjectForKey:@"age" objectClass:[AZInteger class]];
        _gender = [decoder decodeObjectForKey:@"gender" objectClass:[CSCV_Gender class]];
        _faceRectangle = [decoder decodeObjectForKey:@"faceRectangle" objectClass:[CSCV_FaceRectangle class]];
    }
    return self;
}
@end
