/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
*/

#import <AzureClientRuntime/AzureClientRuntime-umbrella.h>
#import "CSCV_Gender.h"
#import "CSCV_FaceRectangle.h"

/**
 * An object describing a face identified in the image.
 */
@interface CSCV_FaceDescription : NSObject <AZCodable>
/**
 * Possible age of the face.
 */
@property AZInteger *age;
/**
 * Possible gender of the face. Possible values include: 'Male', 'Female'.
 */
@property CSCV_Gender *gender;
/**
 * The faceRectangle property.
 */
@property CSCV_FaceRectangle *faceRectangle;
@end
