/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

#import <AzureClientRuntime/AzureClientRuntime-umbrella.h>

/**
 * Defines values for CSCV_Details.
 */
@interface CSCV_Details : NSObject <AZStringEnum>
+ (NSArray*)values;
+ (NSString *)toStringValue:(CSCV_Details *)value;
@property (class, readonly) CSCV_Details *CELEBRITIES;
@property (class, readonly) CSCV_Details *LANDMARKS;
@end
