/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

#import "CSCV_Gender.h"

/**
 * Defines values for CSCV_Gender.
 */
@implementation CSCV_Gender
+ (NSArray*)values {
    static NSArray *allValues;
    static dispatch_once_t onceToken;
    dispatch_once(&onceToken, ^{
        allValues = @[
            @"Male",
            @"Female"
        ];
    });
    return allValues;
}
/** Enum value Male. */
+ (CSCV_Gender*)MALE {
    return [CSCV_Gender values][0];
}
/** Enum value Female. */
+ (CSCV_Gender*)FEMALE {
    return [CSCV_Gender values][1];
}
+ (CSCV_Gender *)fromString:(NSString *)string {
    if (![[CSCV_Gender values]containsObject:string]) {
        @throw [NSException exceptionWithName:@"EnumCastException" reason:@"The string is not the enum member" userInfo:nil];
    }
    return (CSCV_Gender *)string;
}
+ (NSString *)toStringValue:(CSCV_Gender *)value {
    if (![[CSCV_Gender values]containsObject:value]) {
        @throw [NSException exceptionWithName:@"EnumCastException" reason:@"Enum value doesn't exist" userInfo:nil];
    }
    return (NSString *)value;
}
@end
