/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
*/

#import <AzureClientRuntime/AzureClientRuntime-umbrella.h>
#import "CSCV_CelebritiesModel.h"
#import "CSCV_ImageMetadata.h"

/**
 * List of celebrities recognized in the image.
 */
@interface CSCV_CelebrityResults : NSObject <AZCodable>
/**
 * The celebrities property.
 */
@property NSArray<CSCV_CelebritiesModel*> *celebrities;
/**
 * Id of the REST API request.
 */
@property NSString *requestId;
/**
 * The metadata property.
 */
@property CSCV_ImageMetadata *metadata;
@end
