/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

#import "CSCV_ImageMetadata.h"

@implementation CSCV_ImageMetadata
- (void)encodeWithCoder:(id<AZCoder>)encoder {

    [encoder encodeObject:self.width forKey:@"width"];
    [encoder encodeObject:self.height forKey:@"height"];
    [encoder encodeObject:self.format forKey:@"format"];
}
- (nullable instancetype)initWithDecoder:(id<AZCoder>)decoder {

    if (self = [super init]) {
        _width = [decoder decodeObjectForKey:@"width" objectClass:[AZInteger class]];
        _height = [decoder decodeObjectForKey:@"height" objectClass:[AZInteger class]];
        _format = [decoder decodeObjectForKey:@"format" objectClass:[NSString class]];
    }
    return self;
}
@end
