/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
*/

#import <AzureClientRuntime/AzureClientRuntime-umbrella.h>

/**
 * A landmark recognized in the image.
 */
@interface CSCV_LandmarksModel : NSObject <AZCodable>
/**
 * Name of the landmark.
 */
@property NSString *name;
/**
 * Confidence level for the landmark recognition.
 */
@property AZDouble *confidence;
@end
