/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

#import <AzureClientRuntime/AzureClientRuntime-umbrella.h>

/**
 * Defines values for Details.
 */
@interface Details : NSString <StringEnum>

    + (NSArray*) values;

    @property (class, readonly) Details* CELEBRITIES;
    @property (class, readonly) Details* LANDMARKS;

@end
