/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

#import "Details.h"

/**
 * Defines values for Details.
 */
@implementation Details

    + (NSArray*) values {

        static NSArray *allValues;
        static dispatch_once_t onceToken;
        dispatch_once(&onceToken, ^{
            allValues = @[
                @"Celebrities",
                @"Landmarks"
            ];
        });

        return allValues;
    }

    /** Enum value Celebrities. */
    static Details* _CELEBRITIES = (Details*)@"Celebrities";

    + (Details*) CELEBRITIES {
        return _CELEBRITIES;
    }

    /** Enum value Landmarks. */
    static Details* _LANDMARKS = (Details*)@"Landmarks";

    + (Details*) LANDMARKS {
        return _LANDMARKS;
    }

    + (Details *) fromString: (NSString *) string {
        return (Details *) string;
    }

    + (NSString *) toStringValue: (id<StringEnum>) value {
        if (![[Details values] containsObject:value]) {
            @throw [NSException exceptionWithName:@"EnumCastException" reason:@"Enum value doesn't exist" userInfo:nil];
        }

        return (NSString *) value;
    }

@end
