/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
*/

#import <AzureClientRuntime/AzureClientRuntime-umbrella.h>
#import "ImageMetadata.h"

/**
 * Result of image analysis using a specific domain model including additional
 * metadata.
*/
@interface DomainModelResults : NSObject <Codable>

    /**
     * Model-specific response.
    */
    // json "result"
    @property  NSObject* result;

    /**
     * Id of the REST API request.
    */
    // json "requestId"
    @property  NSString* requestId;

    /**
     * The metadata property.
    */
    // json "metadata"
    @property  ImageMetadata* metadata;


@end
