/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

#import "DomainModelResults.h"

@implementation DomainModelResults

- (void)encodeWithCoder:(id<Coder>) encoder {

    [encoder encodeObject: self.result forKey: @"result"];
    [encoder encodeObject: self.requestId forKey: @"requestId"];
    [encoder encodeObject: self.metadata forKey: @"metadata"];

}

- (nullable instancetype)initWithDecoder:(id<Coder>)decoder {

    if (self = [super init]) {

        _result = [decoder decodeObjectForKey:@"result" objectClass:[NSObject class]];
        _requestId = [decoder decodeObjectForKey:@"requestId" objectClass:[NSString class]];
        _metadata = [decoder decodeObjectForKey:@"metadata" objectClass:[ImageMetadata class]];
    }

    return self;
}

@end
