/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

#import "FaceDescription.h"

@implementation FaceDescription

- (void)encodeWithCoder:(id<Coder>) encoder {

    [encoder encodeObject: self.age forKey: @"age"];
    [encoder encodeObject: self.gender forKey: @"gender"];
    [encoder encodeObject: self.faceRectangle forKey: @"faceRectangle"];

}

- (nullable instancetype)initWithDecoder:(id<Coder>)decoder {

    if (self = [super init]) {

        _age = [decoder decodeObjectForKey:@"age" objectClass:[AZInteger class]];
        _gender = [decoder decodeObjectForKey:@"gender" objectClass:[Gender class]];
        _faceRectangle = [decoder decodeObjectForKey:@"faceRectangle" objectClass:[FaceRectangle class]];
    }

    return self;
}

@end
