/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

#import "FaceRectangle.h"

@implementation FaceRectangle

- (void)encodeWithCoder:(id<Coder>) encoder {

    [encoder encodeObject: self.left forKey: @"left"];
    [encoder encodeObject: self.top forKey: @"top"];
    [encoder encodeObject: self.width forKey: @"width"];
    [encoder encodeObject: self.height forKey: @"height"];

}

- (nullable instancetype)initWithDecoder:(id<Coder>)decoder {

    if (self = [super init]) {

        _left = [decoder decodeObjectForKey:@"left" objectClass:[AZInteger class]];
        _top = [decoder decodeObjectForKey:@"top" objectClass:[AZInteger class]];
        _width = [decoder decodeObjectForKey:@"width" objectClass:[AZInteger class]];
        _height = [decoder decodeObjectForKey:@"height" objectClass:[AZInteger class]];
    }

    return self;
}

@end
