/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
*/

#import <AzureClientRuntime/AzureClientRuntime-umbrella.h>
#import "Gender.h"
#import "FaceRectangle.h"

/**
 * An object describing a face identified in the image.
*/
@interface FaceDescription : NSObject <Codable>

    /**
     * Possible age of the face.
    */
    // json "age"
    @property  AZInteger* age;

    /**
     * Possible gender of the face. Possible values include: 'Male', 'Female'.
    */
    // json "gender"
    @property  Gender* gender;

    /**
     * The faceRectangle property.
    */
    // json "faceRectangle"
    @property  FaceRectangle* faceRectangle;


@end
