/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

#import "Gender.h"

/**
 * Defines values for Gender.
 */
@implementation Gender

    + (NSArray*) values {

        static NSArray *allValues;
        static dispatch_once_t onceToken;
        dispatch_once(&onceToken, ^{
            allValues = @[
                @"Male",
                @"Female"
            ];
        });

        return allValues;
    }

    /** Enum value Male. */
    static Gender* _MALE = (Gender*)@"Male";

    + (Gender*) MALE {
        return _MALE;
    }

    /** Enum value Female. */
    static Gender* _FEMALE = (Gender*)@"Female";

    + (Gender*) FEMALE {
        return _FEMALE;
    }

    + (Gender *) fromString: (NSString *) string {
        return (Gender *) string;
    }

    + (NSString *) toStringValue: (id<StringEnum>) value {
        if (![[Gender values] containsObject:value]) {
            @throw [NSException exceptionWithName:@"EnumCastException" reason:@"Enum value doesn't exist" userInfo:nil];
        }

        return (NSString *) value;
    }

@end
