/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

#import <AzureClientRuntime/AzureClientRuntime-umbrella.h>

/**
 * Defines values for Gender.
 */
@interface Gender : NSString <StringEnum>

    + (NSArray*) values;

    @property (class, readonly) Gender* MALE;
    @property (class, readonly) Gender* FEMALE;

@end
