/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
*/

#import <AzureClientRuntime/AzureClientRuntime-umbrella.h>

/**
 * Image metadata.
*/
@interface ImageMetadata : NSObject <Codable>

    /**
     * Image width.
    */
    // json "width"
    @property  AZInteger* width;

    /**
     * Image height.
    */
    // json "height"
    @property  AZInteger* height;

    /**
     * Image format.
    */
    // json "format"
    @property  NSString* format;


@end
