/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

#import "ImageUrl.h"

@implementation ImageUrl

    - (id) initUrl: (NSString *) url {
        self = [super init];
        if (self) {
            _url = url;
        }
        return self;
    }

- (void)encodeWithCoder:(id<Coder>) encoder {

    [encoder encodeObject: self.url forKey: @"url"];

}

- (nullable instancetype)initWithDecoder:(id<Coder>)decoder {

    if (self = [super init]) {

        _url = [decoder decodeObjectForKey:@"url" objectClass:[NSString class]];
    }

    return self;
}

@end
