/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
*/

#import <AzureClientRuntime/AzureClientRuntime-umbrella.h>

/**
 * An image caption, i.e. a brief description of what the image depicts.
*/
@interface ImageTag : NSObject <Codable>

    /**
     * The tag value.
    */
    // json "name"
    @property  NSString* name;

    /**
     * The level of confidence the service has in the caption.
    */
    // json "confidence"
    @property  AZDouble* confidence;

    /**
     * Optional categorization for the tag.
    */
    // json "hint"
    @property  NSString* hint;


@end
