/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

#import "ImageDescriptionDetails.h"

@implementation ImageDescriptionDetails

- (void)encodeWithCoder:(id<Coder>) encoder {

    [encoder encodeObject: self.tags forKey: @"tags"];
    [encoder encodeObject: self.captions forKey: @"captions"];

}

- (nullable instancetype)initWithDecoder:(id<Coder>)decoder {

    if (self = [super init]) {

        _tags = [decoder decodeArrayForKey:@"tags" elementClass:[NSString class]];
        _captions = [decoder decodeArrayForKey:@"captions" elementClass:[ImageCaption class]];
    }

    return self;
}

@end
