/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
*/

#import <AzureClientRuntime/AzureClientRuntime-umbrella.h>
#import "Category.h"
#import "AdultInfo.h"
#import "ColorInfo.h"
#import "ImageType.h"
#import "ImageTag.h"
#import "ImageDescriptionDetails.h"
#import "FaceDescription.h"
#import "ImageMetadata.h"

/**
 * Result of AnalyzeImage operation.
*/
@interface ImageAnalysis : NSObject <Codable>

    /**
     * An array indicating identified categories.
    */
    // json "categories"
    @property  NSArray<Category*>* categories;

    /**
     * The adult property.
    */
    // json "adult"
    @property  AdultInfo* adult;

    /**
     * The color property.
    */
    // json "color"
    @property  ColorInfo* color;

    /**
     * The imageType property.
    */
    // json "imageType"
    @property  ImageType* imageType;

    /**
     * A list of tags with confidence level.
    */
    // json "tags"
    @property  NSArray<ImageTag*>* tags;

    /**
     * The descriptionProperty property.
    */
    // json "description"
    @property  ImageDescriptionDetails* descriptionProperty;

    /**
     * An array of possible faces within the image.
    */
    // json "faces"
    @property  NSArray<FaceDescription*>* faces;

    /**
     * Id of the request for tracking purposes.
    */
    // json "requestId"
    @property  NSString* requestId;

    /**
     * The metadata property.
    */
    // json "metadata"
    @property  ImageMetadata* metadata;


@end
