/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
*/

#import <AzureClientRuntime/AzureClientRuntime-umbrella.h>
#import "ImageCaption.h"

/**
 * A collection of content tags, along with a list of captions sorted by
 * confidence level, and image metadata.
*/
@interface ImageDescriptionDetails : NSObject <Codable>

    /**
     * A collection of image tags.
    */
    // json "tags"
    @property  NSArray<NSString*>* tags;

    /**
     * A list of captions, sorted by confidence level.
    */
    // json "captions"
    @property  NSArray<ImageCaption*>* captions;


@end
