/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
*/

#import <AzureClientRuntime/AzureClientRuntime-umbrella.h>
#import "ImageCaption.h"
#import "ImageMetadata.h"

/**
 * A collection of content tags, along with a list of captions sorted by
 * confidence level, and image metadata.
*/
// Needs Flatten
@interface ImageDescription : NSObject <Codable>

    /**
     * A collection of image tags.
    */
    // json "description.tags"
    @property  NSArray<NSString*>* tags;

    /**
     * A list of captions, sorted by confidence level.
    */
    // json "description.captions"
    @property  NSArray<ImageCaption*>* captions;

    /**
     * Id of the REST API request.
    */
    // json "requestId"
    @property  NSString* requestId;

    /**
     * The metadata property.
    */
    // json "metadata"
    @property  ImageMetadata* metadata;


@end
