/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
*/

#import <AzureClientRuntime/AzureClientRuntime-umbrella.h>

/**
 * A landmark recognized in the image.
*/
@interface LandmarksModel : NSObject <Codable>

    /**
     * Name of the landmark.
    */
    // json "name"
    @property  NSString* name;

    /**
     * Confidence level for the landmark recognition.
    */
    // json "confidence"
    @property  AZDouble* confidence;


@end
