/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

#import "ListModelsResult.h"

@implementation ListModelsResult

    - (id) initModelsProperty: (NSArray<ModelDescription*> *) modelsProperty {
        self = [super init];
        if (self) {
            _modelsProperty = modelsProperty;
        }
        return self;
    }

- (void)encodeWithCoder:(id<Coder>) encoder {


}

- (nullable instancetype)initWithDecoder:(id<Coder>)decoder {

    if (self = [super init]) {

        _modelsProperty = [decoder decodeArrayForKey:@"models" elementClass:[ModelDescription class]];
    }

    return self;
}

@end
