/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
*/

#import <AzureClientRuntime/AzureClientRuntime-umbrella.h>
#import "ModelDescription.h"

/**
 * Result of the List Domain Models operation.
*/
@interface ListModelsResult : NSObject <Codable>

    /**
     * An array of supported models.
    */
    // json "models", access = JsonProperty.Access.WRITE_ONLY
    @property (readonly) NSArray<ModelDescription*>* modelsProperty;

    /**
    * Creates an instance of ListModelsResult class.
    */
    - (id) initModelsProperty: (NSArray<ModelDescription*> *) modelsProperty;


@end
