/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
*/

#import <AzureClientRuntime/AzureClientRuntime-umbrella.h>

/**
 * An object describing supported model by name and categories.
*/
@interface ModelDescription : NSObject <Codable>

    /**
     * The name property.
    */
    // json "name"
    @property  NSString* name;

    /**
     * The categories property.
    */
    // json "categories"
    @property  NSArray<NSString*>* categories;


@end
