/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

#import "ModelDescription.h"

@implementation ModelDescription

- (void)encodeWithCoder:(id<Coder>) encoder {

    [encoder encodeObject: self.name forKey: @"name"];
    [encoder encodeObject: self.categories forKey: @"categories"];

}

- (nullable instancetype)initWithDecoder:(id<Coder>)decoder {

    if (self = [super init]) {

        _name = [decoder decodeObjectForKey:@"name" objectClass:[NSString class]];
        _categories = [decoder decodeArrayForKey:@"categories" elementClass:[NSString class]];
    }

    return self;
}

@end
