/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

#import "OcrLine.h"

@implementation OcrLine

- (void)encodeWithCoder:(id<Coder>) encoder {

    [encoder encodeObject: self.boundingBox forKey: @"boundingBox"];
    [encoder encodeObject: self.words forKey: @"words"];

}

- (nullable instancetype)initWithDecoder:(id<Coder>)decoder {

    if (self = [super init]) {

        _boundingBox = [decoder decodeObjectForKey:@"boundingBox" objectClass:[NSString class]];
        _words = [decoder decodeArrayForKey:@"words" elementClass:[OcrWord class]];
    }

    return self;
}

@end
