/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

#import "OcrRegion.h"

@implementation OcrRegion

- (void)encodeWithCoder:(id<Coder>) encoder {

    [encoder encodeObject: self.boundingBox forKey: @"boundingBox"];
    [encoder encodeObject: self.lines forKey: @"lines"];

}

- (nullable instancetype)initWithDecoder:(id<Coder>)decoder {

    if (self = [super init]) {

        _boundingBox = [decoder decodeObjectForKey:@"boundingBox" objectClass:[NSString class]];
        _lines = [decoder decodeArrayForKey:@"lines" elementClass:[OcrLine class]];
    }

    return self;
}

@end
