/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

#import "OcrWord.h"

@implementation OcrWord

- (void)encodeWithCoder:(id<Coder>) encoder {

    [encoder encodeObject: self.boundingBox forKey: @"boundingBox"];
    [encoder encodeObject: self.text forKey: @"text"];

}

- (nullable instancetype)initWithDecoder:(id<Coder>)decoder {

    if (self = [super init]) {

        _boundingBox = [decoder decodeObjectForKey:@"boundingBox" objectClass:[NSString class]];
        _text = [decoder decodeObjectForKey:@"text" objectClass:[NSString class]];
    }

    return self;
}

@end
