/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

#import "TextRecognitionMode.h"

/**
 * Defines values for TextRecognitionMode.
 */
@implementation TextRecognitionMode

    + (NSArray*) values {

        static NSArray *allValues;
        static dispatch_once_t onceToken;
        dispatch_once(&onceToken, ^{
            allValues = @[
                @"Handwritten",
                @"Printed"
            ];
        });

        return allValues;
    }

    /** Enum value Handwritten. */
    static TextRecognitionMode* _HANDWRITTEN = (TextRecognitionMode*)@"Handwritten";

    + (TextRecognitionMode*) HANDWRITTEN {
        return _HANDWRITTEN;
    }

    /** Enum value Printed. */
    static TextRecognitionMode* _PRINTED = (TextRecognitionMode*)@"Printed";

    + (TextRecognitionMode*) PRINTED {
        return _PRINTED;
    }

    + (TextRecognitionMode *) fromString: (NSString *) string {
        return (TextRecognitionMode *) string;
    }

    + (NSString *) toStringValue: (id<StringEnum>) value {
        if (![[TextRecognitionMode values] containsObject:value]) {
            @throw [NSException exceptionWithName:@"EnumCastException" reason:@"Enum value doesn't exist" userInfo:nil];
        }

        return (NSString *) value;
    }

@end
