/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

#import <AzureClientRuntime/AzureClientRuntime-umbrella.h>

/**
 * Defines values for VisualFeatureTypes.
 */
@interface VisualFeatureTypes : NSString <StringEnum>

    + (NSArray*) values;

    @property (class, readonly) VisualFeatureTypes* IMAGE_TYPE;
    @property (class, readonly) VisualFeatureTypes* FACES;
    @property (class, readonly) VisualFeatureTypes* ADULT;
    @property (class, readonly) VisualFeatureTypes* CATEGORIES;
    @property (class, readonly) VisualFeatureTypes* COLOR;
    @property (class, readonly) VisualFeatureTypes* TAGS;
    @property (class, readonly) VisualFeatureTypes* DESCRIPTION;

@end
